spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/oj_database
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml